name: lamp_shop_app_ui
description: Lamp Shop App UI
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  mockingjay: ^0.3.0

flutter:
  uses-material-design: true
