name: notes_app_ui
description: Notes App UI
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockingjay: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: NeueMontreal
      fonts:
        - asset: assets/fonts/NeueMontreal-Regular.otf
