name: furniture_ecommerce_app_ui
description: Furniture E-commerce App UI
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockingjay: ^0.3.0

flutter:
  uses-material-design: true
